---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-deployment
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  labels:
    app: swiggy
spec:
  type: NodePort
  selector:
    app: swiggy
  ports:
    - port: 80         
      targetPort: 80     
      nodePort: 30007    
