apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: cont-1
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80          # The port on the service
      targetPort: 80     # The container port
      nodePort: 30005    # Optional: Specify a port (range: 30000-32767)
